name: CraftProtect
version: '${project.version}'
main: com.github.oasis.craftprotect.CraftProtectPlugin
api-version: 1.19
authors: [ Oasis, LeBaasti, CyntrixAlgorithm ]
commands:
  uptime:
    usage: '/<command>'
    description: Zeigt deine Spielzeit
  afk:
    usage: '/<command>'
    description: 'Wenn du diesen Befehl ausführst, bekommst du die Rolle AFK'
  sub:
    usage: '/<command>'
  flame:
    usage: '/<command>'
    permission: craftprotect.command.flame
    aliases: [f]
  live:
    usage: /Live
    aliases:
      - l
  reset:
    usage: /reset
    aliases:
      - r
  oasislive:
    usage: '/<command>'
    permission: 'cp4.admin'
    aliases:
      - ol
  rw:
    usage: '/<command>'
  tanjo:
    usage: '/<command>'
    description: "Du hast das Easteregg aus Cp4 gefunden. Melde dich gerne bei Oasis"
  gui:
    usage: '/<command>'
    description: 'Öffnet das GUI'

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20-RC
  - org.apache.commons:commons-text:1.10.0


